const canadianUtilitiesPhishingDomains = [
  {
    "domain": "enbridge-bill-payment.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-05T12:00:05.706341",
    "source": "utilities_detection",
    "company": "Enbridge",
    "keyword": "enbridge",
    "description": "Phishing domain impersonating Enbridge energy services",
    "sector": "energy"
  },
  {
    "domain": "fortisbc-account.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-05T12:00:05.706453",
    "source": "utilities_detection",
    "company": "Fortis",
    "keyword": "fortis",
    "description": "Phishing domain impersonating Fortis energy services",
    "sector": "energy"
  },
  {
    "domain": "hydroquebec-payment.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-05T12:00:05.706514",
    "source": "utilities_detection",
    "company": "Hydro-Qu\u00e9bec",
    "keyword": "hydroquebec",
    "description": "Phishing domain impersonating Hydro-Qu\u00e9bec services",
    "sector": "hydro"
  },
  {
    "domain": "bchydro-bill.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-05T12:00:05.706594",
    "source": "utilities_detection",
    "company": "BC Hydro",
    "keyword": "bchydro",
    "description": "Phishing domain impersonating BC Hydro services",
    "sector": "hydro"
  },
  {
    "domain": "saskpower-account.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-05T12:00:05.706688",
    "source": "utilities_detection",
    "company": "SaskPower",
    "keyword": "saskpower",
    "description": "Phishing domain impersonating SaskPower services",
    "sector": "hydro"
  },
  {
    "domain": "manitobahydro-payment.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-05T12:00:05.706705",
    "source": "utilities_detection",
    "company": "Manitoba Hydro",
    "keyword": "manitobahydro",
    "description": "Phishing domain impersonating Manitoba Hydro services",
    "sector": "hydro"
  },
  {
    "domain": "hydroone-bill.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-05T12:00:05.706716",
    "source": "utilities_detection",
    "company": "Hydro One",
    "keyword": "hydroone",
    "description": "Phishing domain impersonating Hydro One services",
    "sector": "hydro"
  },
  {
    "domain": "torontohydro-payment.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-05T12:00:05.706851",
    "source": "utilities_detection",
    "company": "Toronto Hydro",
    "keyword": "torontohydro",
    "description": "Phishing domain impersonating Toronto Hydro services",
    "sector": "hydro"
  },
  {
    "domain": "alectra-account.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-05T12:00:05.706905",
    "source": "utilities_detection",
    "company": "Alectra",
    "keyword": "alectra",
    "description": "Phishing domain impersonating Alectra utility services",
    "sector": "utilities"
  },
  {
    "domain": "epcor-bill.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-05T12:00:05.706927",
    "source": "utilities_detection",
    "company": "EPCOR",
    "keyword": "epcor",
    "description": "Phishing domain impersonating EPCOR utility services",
    "sector": "utilities"
  },
  {
    "domain": "newfoundlandpower-payment.com",
    "category": "utilities",
    "score": 10.0,
    "detected_at": "2025-09-05T12:00:05.707764",
    "source": "utilities_detection",
    "company": "Unknown",
    "keyword": "Unknown",
    "description": "Phishing domain targeting Canadian utility services",
    "sector": "utilities"
  },
  {
    "domain": "hydroquebec-verify.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-05T12:00:05.707783",
    "source": "utilities_detection",
    "company": "Hydro-Qu\u00e9bec",
    "keyword": "hydroquebec",
    "description": "Phishing domain impersonating Hydro-Qu\u00e9bec services",
    "sector": "hydro"
  },
  {
    "domain": "bchydro-verify.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-05T12:00:05.707796",
    "source": "utilities_detection",
    "company": "BC Hydro",
    "keyword": "bchydro",
    "description": "Phishing domain impersonating BC Hydro services",
    "sector": "hydro"
  },
  {
    "domain": "saskpower-verify.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-05T12:00:05.707823",
    "source": "utilities_detection",
    "company": "SaskPower",
    "keyword": "saskpower",
    "description": "Phishing domain impersonating SaskPower services",
    "sector": "hydro"
  },
  {
    "domain": "manitobahydro-verify.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-05T12:00:05.707836",
    "source": "utilities_detection",
    "company": "Manitoba Hydro",
    "keyword": "manitobahydro",
    "description": "Phishing domain impersonating Manitoba Hydro services",
    "sector": "hydro"
  },
  {
    "domain": "bell-account-verify.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-05T12:00:05.707852",
    "source": "utilities_detection",
    "company": "Bell Canada",
    "keyword": "bell",
    "description": "Phishing domain impersonating Bell Canada telecom services",
    "sector": "telecom"
  },
  {
    "domain": "rogers-secure-login.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-05T12:00:05.707868",
    "source": "utilities_detection",
    "company": "Rogers Communications",
    "keyword": "rogers",
    "description": "Phishing domain impersonating Rogers Communications services",
    "sector": "telecom"
  },
  {
    "domain": "telus-verify.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-05T12:00:05.707884",
    "source": "utilities_detection",
    "company": "Telus",
    "keyword": "telus",
    "description": "Phishing domain impersonating Telus telecom services",
    "sector": "telecom"
  },
  {
    "domain": "shaw-account-update.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-05T12:00:05.707907",
    "source": "utilities_detection",
    "company": "Shaw Communications",
    "keyword": "shaw",
    "description": "Phishing domain impersonating Shaw Communications services",
    "sector": "telecom"
  },
  {
    "domain": "cogeco-secure.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-05T12:00:05.707925",
    "source": "utilities_detection",
    "company": "Cogeco",
    "keyword": "cogeco",
    "description": "Phishing domain impersonating Cogeco telecom services",
    "sector": "telecom"
  },
  {
    "domain": "videotron-verify.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-05T12:00:05.707943",
    "source": "utilities_detection",
    "company": "Videotron",
    "keyword": "videotron",
    "description": "Phishing domain impersonating Videotron telecom services",
    "sector": "telecom"
  },
  {
    "domain": "freedommobile-secure.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-05T12:00:05.707966",
    "source": "utilities_detection",
    "company": "Freedom Mobile",
    "keyword": "freedommobile",
    "description": "Phishing domain impersonating Freedom Mobile services",
    "sector": "telecom"
  },
  {
    "domain": "koodo-verify.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-05T12:00:05.707985",
    "source": "utilities_detection",
    "company": "Koodo Mobile",
    "keyword": "koodo",
    "description": "Phishing domain impersonating Koodo Mobile services",
    "sector": "telecom"
  },
  {
    "domain": "virginmobile-secure.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-05T12:00:05.708005",
    "source": "utilities_detection",
    "company": "Virgin Mobile Canada",
    "keyword": "virginmobile",
    "description": "Phishing domain impersonating Virgin Mobile Canada services",
    "sector": "telecom"
  },
  {
    "domain": "fido-account-update.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-05T12:00:05.708026",
    "source": "utilities_detection",
    "company": "Fido",
    "keyword": "fido",
    "description": "Phishing domain impersonating Fido mobile services",
    "sector": "telecom"
  },
  {
    "domain": "chatr-secure.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-05T12:00:05.708046",
    "source": "utilities_detection",
    "company": "Chatr",
    "keyword": "chatr",
    "description": "Phishing domain impersonating Chatr mobile services",
    "sector": "telecom"
  },
  {
    "domain": "publicmobile-verify.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-05T12:00:05.708069",
    "source": "utilities_detection",
    "company": "Public Mobile",
    "keyword": "publicmobile",
    "description": "Phishing domain impersonating Public Mobile services",
    "sector": "telecom"
  },
  {
    "domain": "bell-secure-login.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-05T12:00:05.708097",
    "source": "utilities_detection",
    "company": "Bell Canada",
    "keyword": "bell",
    "description": "Phishing domain impersonating Bell Canada telecom services",
    "sector": "telecom"
  },
  {
    "domain": "rogers-verify.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-05T12:00:05.708127",
    "source": "utilities_detection",
    "company": "Rogers Communications",
    "keyword": "rogers",
    "description": "Phishing domain impersonating Rogers Communications services",
    "sector": "telecom"
  },
  {
    "domain": "telus-secure-login.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-05T12:00:05.708165",
    "source": "utilities_detection",
    "company": "Telus",
    "keyword": "telus",
    "description": "Phishing domain impersonating Telus telecom services",
    "sector": "telecom"
  },
  {
    "domain": "shaw-verify.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-05T12:00:05.708197",
    "source": "utilities_detection",
    "company": "Shaw Communications",
    "keyword": "shaw",
    "description": "Phishing domain impersonating Shaw Communications services",
    "sector": "telecom"
  },
  {
    "domain": "cogeco-verify.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-05T12:00:05.708232",
    "source": "utilities_detection",
    "company": "Cogeco",
    "keyword": "cogeco",
    "description": "Phishing domain impersonating Cogeco telecom services",
    "sector": "telecom"
  },
  {
    "domain": "videotron-secure-login.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-05T12:00:05.708267",
    "source": "utilities_detection",
    "company": "Videotron",
    "keyword": "videotron",
    "description": "Phishing domain impersonating Videotron telecom services",
    "sector": "telecom"
  },
  {
    "domain": "enbridge-verify.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-05T12:00:05.708278",
    "source": "utilities_detection",
    "company": "Enbridge",
    "keyword": "enbridge",
    "description": "Phishing domain impersonating Enbridge energy services",
    "sector": "energy"
  },
  {
    "domain": "fortisbc-verify.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-05T12:00:05.708294",
    "source": "utilities_detection",
    "company": "Fortis",
    "keyword": "fortis",
    "description": "Phishing domain impersonating Fortis energy services",
    "sector": "energy"
  },
  {
    "domain": "fortisalberta-verify.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-05T12:00:05.708304",
    "source": "utilities_detection",
    "company": "Fortis",
    "keyword": "fortis",
    "description": "Phishing domain impersonating Fortis energy services",
    "sector": "energy"
  },
  {
    "domain": "atcoelectric-verify.com",
    "category": "utilities",
    "score": 10.0,
    "detected_at": "2025-09-05T12:00:05.708481",
    "source": "utilities_detection",
    "company": "Unknown",
    "keyword": "Unknown",
    "description": "Phishing domain targeting Canadian utility services",
    "sector": "utilities"
  },
  {
    "domain": "epcor-verify.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-05T12:00:05.708499",
    "source": "utilities_detection",
    "company": "EPCOR",
    "keyword": "epcor",
    "description": "Phishing domain impersonating EPCOR utility services",
    "sector": "utilities"
  },
  {
    "domain": "transalta-verify.com",
    "category": "utilities",
    "score": 10.0,
    "detected_at": "2025-09-05T12:00:05.708529",
    "source": "utilities_detection",
    "company": "Unknown",
    "keyword": "Unknown",
    "description": "Phishing domain targeting Canadian utility services",
    "sector": "utilities"
  },
  {
    "domain": "capitalpower-verify.com",
    "category": "utilities",
    "score": 10.0,
    "detected_at": "2025-09-05T12:00:05.708568",
    "source": "utilities_detection",
    "company": "Unknown",
    "keyword": "Unknown",
    "description": "Phishing domain targeting Canadian utility services",
    "sector": "utilities"
  },
  {
    "domain": "brookfieldrenewable-verify.com",
    "category": "utilities",
    "score": 10.0,
    "detected_at": "2025-09-05T12:00:05.708623",
    "source": "utilities_detection",
    "company": "Unknown",
    "keyword": "Unknown",
    "description": "Phishing domain targeting Canadian utility services",
    "sector": "utilities"
  },
  {
    "domain": "utility-bill-payment.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-05T12:00:05.708678",
    "source": "utilities_detection",
    "company": "Generic Utility",
    "keyword": "utility",
    "description": "Phishing domain using generic utility terms",
    "sector": "utilities"
  },
  {
    "domain": "utility-account-verify.com",
    "category": "utilities",
    "score": 10.0,
    "detected_at": "2025-09-05T12:00:05.708737",
    "source": "utilities_detection",
    "company": "Unknown",
    "keyword": "Unknown",
    "description": "Phishing domain targeting Canadian utility services",
    "sector": "utilities"
  },
  {
    "domain": "utility-secure-login.com",
    "category": "utilities",
    "score": 10.0,
    "detected_at": "2025-09-05T12:00:05.708793",
    "source": "utilities_detection",
    "company": "Unknown",
    "keyword": "Unknown",
    "description": "Phishing domain targeting Canadian utility services",
    "sector": "utilities"
  },
  {
    "domain": "utility-verify.com",
    "category": "utilities",
    "score": 10.0,
    "detected_at": "2025-09-05T12:00:05.708836",
    "source": "utilities_detection",
    "company": "Unknown",
    "keyword": "Unknown",
    "description": "Phishing domain targeting Canadian utility services",
    "sector": "utilities"
  },
  {
    "domain": "utility-secure.com",
    "category": "utilities",
    "score": 10.0,
    "detected_at": "2025-09-05T12:00:05.708866",
    "source": "utilities_detection",
    "company": "Unknown",
    "keyword": "Unknown",
    "description": "Phishing domain targeting Canadian utility services",
    "sector": "utilities"
  },
  {
    "domain": "utility-account-update.com",
    "category": "utilities",
    "score": 10.0,
    "detected_at": "2025-09-05T12:00:05.708896",
    "source": "utilities_detection",
    "company": "Unknown",
    "keyword": "Unknown",
    "description": "Phishing domain targeting Canadian utility services",
    "sector": "utilities"
  }
];
export default canadianUtilitiesPhishingDomains;
