const canadianUtilitiesPhishingDomains = [
  {
    "domain": "epcor-verify.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-01T15:49:58.559372",
    "source": "utilities_detection",
    "company": "EPCOR",
    "keyword": "epcor",
    "description": "Phishing domain impersonating EPCOR utility services",
    "sector": "utilities"
  },
  {
    "domain": "manitobahydro-payment.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-01T15:49:58.559415",
    "source": "utilities_detection",
    "company": "Manitoba Hydro",
    "keyword": "manitobahydro",
    "description": "Phishing domain impersonating Manitoba Hydro services",
    "sector": "hydro"
  },
  {
    "domain": "shaw-account-update.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-01T15:49:58.559617",
    "source": "utilities_detection",
    "company": "Shaw Communications",
    "keyword": "shaw",
    "description": "Phishing domain impersonating Shaw Communications services",
    "sector": "telecom"
  },
  {
    "domain": "bell-secure-login.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-01T15:49:58.559642",
    "source": "utilities_detection",
    "company": "Bell Canada",
    "keyword": "bell",
    "description": "Phishing domain impersonating Bell Canada telecom services",
    "sector": "telecom"
  },
  {
    "domain": "hydroquebec-verify.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-01T15:49:58.559655",
    "source": "utilities_detection",
    "company": "Hydro-Qu\u00e9bec",
    "keyword": "hydroquebec",
    "description": "Phishing domain impersonating Hydro-Qu\u00e9bec services",
    "sector": "hydro"
  },
  {
    "domain": "fortisbc-verify.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-01T15:49:58.559687",
    "source": "utilities_detection",
    "company": "Fortis",
    "keyword": "fortis",
    "description": "Phishing domain impersonating Fortis energy services",
    "sector": "energy"
  },
  {
    "domain": "koodo-verify.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-01T15:49:58.559854",
    "source": "utilities_detection",
    "company": "Koodo Mobile",
    "keyword": "koodo",
    "description": "Phishing domain impersonating Koodo Mobile services",
    "sector": "telecom"
  },
  {
    "domain": "bchydro-bill.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-01T15:49:58.559883",
    "source": "utilities_detection",
    "company": "BC Hydro",
    "keyword": "bchydro",
    "description": "Phishing domain impersonating BC Hydro services",
    "sector": "hydro"
  },
  {
    "domain": "hydroone-bill.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-01T15:49:58.559914",
    "source": "utilities_detection",
    "company": "Hydro One",
    "keyword": "hydroone",
    "description": "Phishing domain impersonating Hydro One services",
    "sector": "hydro"
  },
  {
    "domain": "bchydro-verify.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-01T15:49:58.559937",
    "source": "utilities_detection",
    "company": "BC Hydro",
    "keyword": "bchydro",
    "description": "Phishing domain impersonating BC Hydro services",
    "sector": "hydro"
  },
  {
    "domain": "rogers-verify.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-01T15:49:58.559962",
    "source": "utilities_detection",
    "company": "Rogers Communications",
    "keyword": "rogers",
    "description": "Phishing domain impersonating Rogers Communications services",
    "sector": "telecom"
  },
  {
    "domain": "utility-bill-payment.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-01T15:49:58.560446",
    "source": "utilities_detection",
    "company": "Generic Utility",
    "keyword": "utility",
    "description": "Phishing domain using generic utility terms",
    "sector": "utilities"
  },
  {
    "domain": "atcoelectric-verify.com",
    "category": "utilities",
    "score": 10.0,
    "detected_at": "2025-09-01T15:49:58.560750",
    "source": "utilities_detection",
    "company": "Unknown",
    "keyword": "Unknown",
    "description": "Phishing domain targeting Canadian utility services",
    "sector": "utilities"
  },
  {
    "domain": "epcor-bill.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-01T15:49:58.560772",
    "source": "utilities_detection",
    "company": "EPCOR",
    "keyword": "epcor",
    "description": "Phishing domain impersonating EPCOR utility services",
    "sector": "utilities"
  },
  {
    "domain": "hydroquebec-payment.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-01T15:49:58.560785",
    "source": "utilities_detection",
    "company": "Hydro-Qu\u00e9bec",
    "keyword": "hydroquebec",
    "description": "Phishing domain impersonating Hydro-Qu\u00e9bec services",
    "sector": "hydro"
  },
  {
    "domain": "newfoundlandpower-payment.com",
    "category": "utilities",
    "score": 10.0,
    "detected_at": "2025-09-01T15:49:58.560820",
    "source": "utilities_detection",
    "company": "Unknown",
    "keyword": "Unknown",
    "description": "Phishing domain targeting Canadian utility services",
    "sector": "utilities"
  },
  {
    "domain": "videotron-verify.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-01T15:49:58.560842",
    "source": "utilities_detection",
    "company": "Videotron",
    "keyword": "videotron",
    "description": "Phishing domain impersonating Videotron telecom services",
    "sector": "telecom"
  },
  {
    "domain": "cogeco-secure.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-01T15:49:58.560862",
    "source": "utilities_detection",
    "company": "Cogeco",
    "keyword": "cogeco",
    "description": "Phishing domain impersonating Cogeco telecom services",
    "sector": "telecom"
  },
  {
    "domain": "videotron-secure-login.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-01T15:49:58.560884",
    "source": "utilities_detection",
    "company": "Videotron",
    "keyword": "videotron",
    "description": "Phishing domain impersonating Videotron telecom services",
    "sector": "telecom"
  },
  {
    "domain": "fortisalberta-verify.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-01T15:49:58.560895",
    "source": "utilities_detection",
    "company": "Fortis",
    "keyword": "fortis",
    "description": "Phishing domain impersonating Fortis energy services",
    "sector": "energy"
  },
  {
    "domain": "rogers-secure-login.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-01T15:49:58.560926",
    "source": "utilities_detection",
    "company": "Rogers Communications",
    "keyword": "rogers",
    "description": "Phishing domain impersonating Rogers Communications services",
    "sector": "telecom"
  },
  {
    "domain": "publicmobile-verify.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-01T15:49:58.560952",
    "source": "utilities_detection",
    "company": "Public Mobile",
    "keyword": "publicmobile",
    "description": "Phishing domain impersonating Public Mobile services",
    "sector": "telecom"
  },
  {
    "domain": "saskpower-verify.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-01T15:49:58.560968",
    "source": "utilities_detection",
    "company": "SaskPower",
    "keyword": "saskpower",
    "description": "Phishing domain impersonating SaskPower services",
    "sector": "hydro"
  },
  {
    "domain": "fortisbc-account.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-01T15:49:58.560993",
    "source": "utilities_detection",
    "company": "Fortis",
    "keyword": "fortis",
    "description": "Phishing domain impersonating Fortis energy services",
    "sector": "energy"
  },
  {
    "domain": "freedommobile-secure.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-01T15:49:58.561031",
    "source": "utilities_detection",
    "company": "Freedom Mobile",
    "keyword": "freedommobile",
    "description": "Phishing domain impersonating Freedom Mobile services",
    "sector": "telecom"
  },
  {
    "domain": "manitobahydro-verify.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-01T15:49:58.561054",
    "source": "utilities_detection",
    "company": "Manitoba Hydro",
    "keyword": "manitobahydro",
    "description": "Phishing domain impersonating Manitoba Hydro services",
    "sector": "hydro"
  },
  {
    "domain": "utility-account-update.com",
    "category": "utilities",
    "score": 10.0,
    "detected_at": "2025-09-01T15:49:58.561181",
    "source": "utilities_detection",
    "company": "Unknown",
    "keyword": "Unknown",
    "description": "Phishing domain targeting Canadian utility services",
    "sector": "utilities"
  },
  {
    "domain": "alectra-account.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-01T15:49:58.561209",
    "source": "utilities_detection",
    "company": "Alectra",
    "keyword": "alectra",
    "description": "Phishing domain impersonating Alectra utility services",
    "sector": "utilities"
  },
  {
    "domain": "torontohydro-payment.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-01T15:49:58.561237",
    "source": "utilities_detection",
    "company": "Toronto Hydro",
    "keyword": "torontohydro",
    "description": "Phishing domain impersonating Toronto Hydro services",
    "sector": "hydro"
  },
  {
    "domain": "virginmobile-secure.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-01T15:49:58.561274",
    "source": "utilities_detection",
    "company": "Virgin Mobile Canada",
    "keyword": "virginmobile",
    "description": "Phishing domain impersonating Virgin Mobile Canada services",
    "sector": "telecom"
  },
  {
    "domain": "chatr-secure.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-01T15:49:58.561308",
    "source": "utilities_detection",
    "company": "Chatr",
    "keyword": "chatr",
    "description": "Phishing domain impersonating Chatr mobile services",
    "sector": "telecom"
  },
  {
    "domain": "saskpower-account.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-01T15:49:58.561321",
    "source": "utilities_detection",
    "company": "SaskPower",
    "keyword": "saskpower",
    "description": "Phishing domain impersonating SaskPower services",
    "sector": "hydro"
  },
  {
    "domain": "brookfieldrenewable-verify.com",
    "category": "utilities",
    "score": 10.0,
    "detected_at": "2025-09-01T15:49:58.561356",
    "source": "utilities_detection",
    "company": "Unknown",
    "keyword": "Unknown",
    "description": "Phishing domain targeting Canadian utility services",
    "sector": "utilities"
  },
  {
    "domain": "fido-account-update.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-01T15:49:58.561379",
    "source": "utilities_detection",
    "company": "Fido",
    "keyword": "fido",
    "description": "Phishing domain impersonating Fido mobile services",
    "sector": "telecom"
  },
  {
    "domain": "bell-account-verify.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-01T15:49:58.561397",
    "source": "utilities_detection",
    "company": "Bell Canada",
    "keyword": "bell",
    "description": "Phishing domain impersonating Bell Canada telecom services",
    "sector": "telecom"
  },
  {
    "domain": "cogeco-verify.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-01T15:49:58.561416",
    "source": "utilities_detection",
    "company": "Cogeco",
    "keyword": "cogeco",
    "description": "Phishing domain impersonating Cogeco telecom services",
    "sector": "telecom"
  },
  {
    "domain": "utility-verify.com",
    "category": "utilities",
    "score": 10.0,
    "detected_at": "2025-09-01T15:49:58.561459",
    "source": "utilities_detection",
    "company": "Unknown",
    "keyword": "Unknown",
    "description": "Phishing domain targeting Canadian utility services",
    "sector": "utilities"
  },
  {
    "domain": "telus-verify.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-01T15:49:58.561485",
    "source": "utilities_detection",
    "company": "Telus",
    "keyword": "telus",
    "description": "Phishing domain impersonating Telus telecom services",
    "sector": "telecom"
  },
  {
    "domain": "utility-secure.com",
    "category": "utilities",
    "score": 10.0,
    "detected_at": "2025-09-01T15:49:58.561540",
    "source": "utilities_detection",
    "company": "Unknown",
    "keyword": "Unknown",
    "description": "Phishing domain targeting Canadian utility services",
    "sector": "utilities"
  },
  {
    "domain": "telus-secure-login.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-01T15:49:58.561570",
    "source": "utilities_detection",
    "company": "Telus",
    "keyword": "telus",
    "description": "Phishing domain impersonating Telus telecom services",
    "sector": "telecom"
  },
  {
    "domain": "utility-secure-login.com",
    "category": "utilities",
    "score": 10.0,
    "detected_at": "2025-09-01T15:49:58.561623",
    "source": "utilities_detection",
    "company": "Unknown",
    "keyword": "Unknown",
    "description": "Phishing domain targeting Canadian utility services",
    "sector": "utilities"
  },
  {
    "domain": "capitalpower-verify.com",
    "category": "utilities",
    "score": 10.0,
    "detected_at": "2025-09-01T15:49:58.561664",
    "source": "utilities_detection",
    "company": "Unknown",
    "keyword": "Unknown",
    "description": "Phishing domain targeting Canadian utility services",
    "sector": "utilities"
  },
  {
    "domain": "utility-account-verify.com",
    "category": "utilities",
    "score": 10.0,
    "detected_at": "2025-09-01T15:49:58.561699",
    "source": "utilities_detection",
    "company": "Unknown",
    "keyword": "Unknown",
    "description": "Phishing domain targeting Canadian utility services",
    "sector": "utilities"
  },
  {
    "domain": "enbridge-verify.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-01T15:49:58.561713",
    "source": "utilities_detection",
    "company": "Enbridge",
    "keyword": "enbridge",
    "description": "Phishing domain impersonating Enbridge energy services",
    "sector": "energy"
  },
  {
    "domain": "transalta-verify.com",
    "category": "utilities",
    "score": 10.0,
    "detected_at": "2025-09-01T15:49:58.561745",
    "source": "utilities_detection",
    "company": "Unknown",
    "keyword": "Unknown",
    "description": "Phishing domain targeting Canadian utility services",
    "sector": "utilities"
  },
  {
    "domain": "enbridge-bill-payment.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-01T15:49:58.561756",
    "source": "utilities_detection",
    "company": "Enbridge",
    "keyword": "enbridge",
    "description": "Phishing domain impersonating Enbridge energy services",
    "sector": "energy"
  },
  {
    "domain": "shaw-verify.com",
    "category": "utilities",
    "score": 13.0,
    "detected_at": "2025-09-01T15:49:58.561774",
    "source": "utilities_detection",
    "company": "Shaw Communications",
    "keyword": "shaw",
    "description": "Phishing domain impersonating Shaw Communications services",
    "sector": "telecom"
  }
];
export default canadianUtilitiesPhishingDomains;
