const governmentPhishingDomains = [
  {
    "domain": "etransferdeposit25.com",
    "category": "government",
    "score": 10.0,
    "detected_at": "2025-09-04T00:00:06.267745",
    "source": "government_detection",
    "company": "Unknown",
    "keyword": "Unknown",
    "description": "Phishing domain targeting Canadian government services",
    "sector": "government"
  },
  {
    "domain": "reviewgsthstca.com",
    "category": "government",
    "score": 10.0,
    "detected_at": "2025-09-04T00:00:06.267808",
    "source": "government_detection",
    "company": "Unknown",
    "keyword": "Unknown",
    "description": "Phishing domain targeting Canadian government services",
    "sector": "government"
  },
  {
    "domain": "hstcra.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.267821",
    "source": "government_detection",
    "company": "Canada Revenue Agency (CRA)",
    "keyword": "cra",
    "description": "Phishing domain impersonating Canada Revenue Agency services",
    "sector": "federal"
  },
  {
    "domain": "authhstdeposit.com",
    "category": "government",
    "score": 10.0,
    "detected_at": "2025-09-04T00:00:06.267860",
    "source": "government_detection",
    "company": "Unknown",
    "keyword": "Unknown",
    "description": "Phishing domain targeting Canadian government services",
    "sector": "government"
  },
  {
    "domain": "cra-refund-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.267870",
    "source": "government_detection",
    "company": "Canada Revenue Agency (CRA)",
    "keyword": "cra",
    "description": "Phishing domain impersonating Canada Revenue Agency services",
    "sector": "federal"
  },
  {
    "domain": "cra-gst-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.267880",
    "source": "government_detection",
    "company": "Canada Revenue Agency (CRA)",
    "keyword": "cra",
    "description": "Phishing domain impersonating Canada Revenue Agency services",
    "sector": "federal"
  },
  {
    "domain": "cra-hst-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.267888",
    "source": "government_detection",
    "company": "Canada Revenue Agency (CRA)",
    "keyword": "cra",
    "description": "Phishing domain impersonating Canada Revenue Agency services",
    "sector": "federal"
  },
  {
    "domain": "cra-account-secure.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.267898",
    "source": "government_detection",
    "company": "Canada Revenue Agency (CRA)",
    "keyword": "cra",
    "description": "Phishing domain impersonating Canada Revenue Agency services",
    "sector": "federal"
  },
  {
    "domain": "cra-login-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.267907",
    "source": "government_detection",
    "company": "Canada Revenue Agency (CRA)",
    "keyword": "cra",
    "description": "Phishing domain impersonating Canada Revenue Agency services",
    "sector": "federal"
  },
  {
    "domain": "cra-secure-login.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.267916",
    "source": "government_detection",
    "company": "Canada Revenue Agency (CRA)",
    "keyword": "cra",
    "description": "Phishing domain impersonating Canada Revenue Agency services",
    "sector": "federal"
  },
  {
    "domain": "cra-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.267924",
    "source": "government_detection",
    "company": "Canada Revenue Agency (CRA)",
    "keyword": "cra",
    "description": "Phishing domain impersonating Canada Revenue Agency services",
    "sector": "federal"
  },
  {
    "domain": "cra-secure.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.267933",
    "source": "government_detection",
    "company": "Canada Revenue Agency (CRA)",
    "keyword": "cra",
    "description": "Phishing domain impersonating Canada Revenue Agency services",
    "sector": "federal"
  },
  {
    "domain": "cra-account-update.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.267942",
    "source": "government_detection",
    "company": "Canada Revenue Agency (CRA)",
    "keyword": "cra",
    "description": "Phishing domain impersonating Canada Revenue Agency services",
    "sector": "federal"
  },
  {
    "domain": "cra-mobile-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.267951",
    "source": "government_detection",
    "company": "Canada Revenue Agency (CRA)",
    "keyword": "cra",
    "description": "Phishing domain impersonating Canada Revenue Agency services",
    "sector": "federal"
  },
  {
    "domain": "cra-online-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.267959",
    "source": "government_detection",
    "company": "Canada Revenue Agency (CRA)",
    "keyword": "cra",
    "description": "Phishing domain impersonating Canada Revenue Agency services",
    "sector": "federal"
  },
  {
    "domain": "canpost-orderinfo-help.com",
    "category": "government",
    "score": 10.0,
    "detected_at": "2025-09-04T00:00:06.267998",
    "source": "government_detection",
    "company": "Unknown",
    "keyword": "Unknown",
    "description": "Phishing domain targeting Canadian government services",
    "sector": "government"
  },
  {
    "domain": "canadapost-packagereschedule.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.268008",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "redelivercadpost.com",
    "category": "government",
    "score": 10.0,
    "detected_at": "2025-09-04T00:00:06.268046",
    "source": "government_detection",
    "company": "Unknown",
    "keyword": "Unknown",
    "description": "Phishing domain targeting Canadian government services",
    "sector": "government"
  },
  {
    "domain": "setup-canada6517-post4278-now.com",
    "category": "government",
    "score": 14.0,
    "detected_at": "2025-09-04T00:00:06.268056",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "redelivauth.com",
    "category": "government",
    "score": 10.0,
    "detected_at": "2025-09-04T00:00:06.268093",
    "source": "government_detection",
    "company": "Unknown",
    "keyword": "Unknown",
    "description": "Phishing domain targeting Canadian government services",
    "sector": "government"
  },
  {
    "domain": "canadapost-tracking.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.268107",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "canadapost-delivery.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.268124",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "canadapost-package.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.268249",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "canadapost-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.268261",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "canadapost-secure.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.268270",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "canadapost-login.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.268278",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "canadapost-account.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.268297",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "gov-canada-eta.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.268305",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "canada-etavisa.info",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.268314",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "canada-immigration-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.268325",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "canada-passport-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.268334",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "canada-visa-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.268342",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "canada-eta-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.268351",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "canada-immigration-secure.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.268360",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "canada-passport-secure.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.268369",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "canada-visa-secure.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.268381",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "canada-eta-secure.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.268390",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "ontario-license-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.268469",
    "source": "government_detection",
    "company": "Government of Ontario",
    "keyword": "ontario",
    "description": "Phishing domain impersonating Government of Ontario services",
    "sector": "provincial"
  },
  {
    "domain": "ontario-health-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.268489",
    "source": "government_detection",
    "company": "Government of Ontario",
    "keyword": "ontario",
    "description": "Phishing domain impersonating Government of Ontario services",
    "sector": "provincial"
  },
  {
    "domain": "quebec-services-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.268506",
    "source": "government_detection",
    "company": "Government of Quebec",
    "keyword": "quebec",
    "description": "Phishing domain impersonating Government of Quebec services",
    "sector": "provincial"
  },
  {
    "domain": "alberta-account-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.268539",
    "source": "government_detection",
    "company": "Government of Alberta",
    "keyword": "alberta",
    "description": "Phishing domain impersonating Government of Alberta services",
    "sector": "provincial"
  },
  {
    "domain": "bc-services-verify.com",
    "category": "government",
    "score": 10.0,
    "detected_at": "2025-09-04T00:00:06.268581",
    "source": "government_detection",
    "company": "Unknown",
    "keyword": "Unknown",
    "description": "Phishing domain targeting Canadian government services",
    "sector": "government"
  },
  {
    "domain": "ontario-secure.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.268597",
    "source": "government_detection",
    "company": "Government of Ontario",
    "keyword": "ontario",
    "description": "Phishing domain impersonating Government of Ontario services",
    "sector": "provincial"
  },
  {
    "domain": "quebec-secure.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.268614",
    "source": "government_detection",
    "company": "Government of Quebec",
    "keyword": "quebec",
    "description": "Phishing domain impersonating Government of Quebec services",
    "sector": "provincial"
  },
  {
    "domain": "alberta-secure.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.268631",
    "source": "government_detection",
    "company": "Government of Alberta",
    "keyword": "alberta",
    "description": "Phishing domain impersonating Government of Alberta services",
    "sector": "provincial"
  },
  {
    "domain": "bc-secure.com",
    "category": "government",
    "score": 10.0,
    "detected_at": "2025-09-04T00:00:06.268669",
    "source": "government_detection",
    "company": "Unknown",
    "keyword": "Unknown",
    "description": "Phishing domain targeting Canadian government services",
    "sector": "government"
  },
  {
    "domain": "ontario-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.268686",
    "source": "government_detection",
    "company": "Government of Ontario",
    "keyword": "ontario",
    "description": "Phishing domain impersonating Government of Ontario services",
    "sector": "provincial"
  },
  {
    "domain": "quebec-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.268703",
    "source": "government_detection",
    "company": "Government of Quebec",
    "keyword": "quebec",
    "description": "Phishing domain impersonating Government of Quebec services",
    "sector": "provincial"
  },
  {
    "domain": "alberta-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.268730",
    "source": "government_detection",
    "company": "Government of Alberta",
    "keyword": "alberta",
    "description": "Phishing domain impersonating Government of Alberta services",
    "sector": "provincial"
  },
  {
    "domain": "bc-verify.com",
    "category": "government",
    "score": 10.0,
    "detected_at": "2025-09-04T00:00:06.268768",
    "source": "government_detection",
    "company": "Unknown",
    "keyword": "Unknown",
    "description": "Phishing domain targeting Canadian government services",
    "sector": "government"
  },
  {
    "domain": "servicecanada-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.268778",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "elections-canada-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.268790",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "rcmp-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.268803",
    "source": "government_detection",
    "company": "Royal Canadian Mounted Police (RCMP)",
    "keyword": "rcmp",
    "description": "Phishing domain impersonating RCMP services",
    "sector": "federal"
  },
  {
    "domain": "canada-border-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.268813",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "canada-transport-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.268824",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "servicecanada-secure.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.268833",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "elections-canada-secure.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.268842",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "rcmp-secure.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.268855",
    "source": "government_detection",
    "company": "Royal Canadian Mounted Police (RCMP)",
    "keyword": "rcmp",
    "description": "Phishing domain impersonating RCMP services",
    "sector": "federal"
  },
  {
    "domain": "canada-border-secure.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.268864",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "canada-transport-secure.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.268874",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "servicecanada-login.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.268883",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "elections-canada-login.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.268895",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "rcmp-login.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.268908",
    "source": "government_detection",
    "company": "Royal Canadian Mounted Police (RCMP)",
    "keyword": "rcmp",
    "description": "Phishing domain impersonating RCMP services",
    "sector": "federal"
  },
  {
    "domain": "canada-border-login.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.268917",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "canada-transport-login.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-04T00:00:06.268926",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  }
];
export default governmentPhishingDomains;
