const governmentPhishingDomains = [
  {
    "domain": "ontario-secure.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.315031",
    "source": "government_detection",
    "company": "Government of Ontario",
    "keyword": "ontario",
    "description": "Phishing domain impersonating Government of Ontario services",
    "sector": "provincial"
  },
  {
    "domain": "alberta-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.315230",
    "source": "government_detection",
    "company": "Government of Alberta",
    "keyword": "alberta",
    "description": "Phishing domain impersonating Government of Alberta services",
    "sector": "provincial"
  },
  {
    "domain": "cra-online-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.315248",
    "source": "government_detection",
    "company": "Canada Revenue Agency (CRA)",
    "keyword": "cra",
    "description": "Phishing domain impersonating Canada Revenue Agency services",
    "sector": "federal"
  },
  {
    "domain": "canada-visa-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.315262",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "canada-passport-secure.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.315272",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "cra-login-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.315291",
    "source": "government_detection",
    "company": "Canada Revenue Agency (CRA)",
    "keyword": "cra",
    "description": "Phishing domain impersonating Canada Revenue Agency services",
    "sector": "federal"
  },
  {
    "domain": "canadapost-account.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.315309",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "canada-border-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.315328",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "redelivercadpost.com",
    "category": "government",
    "score": 10.0,
    "detected_at": "2025-09-01T17:30:21.317985",
    "source": "government_detection",
    "company": "Unknown",
    "keyword": "Unknown",
    "description": "Phishing domain targeting Canadian government services",
    "sector": "government"
  },
  {
    "domain": "rcmp-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.318044",
    "source": "government_detection",
    "company": "Royal Canadian Mounted Police (RCMP)",
    "keyword": "rcmp",
    "description": "Phishing domain impersonating RCMP services",
    "sector": "federal"
  },
  {
    "domain": "authhstdeposit.com",
    "category": "government",
    "score": 10.0,
    "detected_at": "2025-09-01T17:30:21.318124",
    "source": "government_detection",
    "company": "Unknown",
    "keyword": "Unknown",
    "description": "Phishing domain targeting Canadian government services",
    "sector": "government"
  },
  {
    "domain": "canadapost-tracking.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.318151",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "canadapost-login.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.318168",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "canada-visa-secure.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.318185",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "servicecanada-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.318202",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "quebec-secure.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.318229",
    "source": "government_detection",
    "company": "Government of Quebec",
    "keyword": "quebec",
    "description": "Phishing domain impersonating Government of Quebec services",
    "sector": "provincial"
  },
  {
    "domain": "bc-secure.com",
    "category": "government",
    "score": 10.0,
    "detected_at": "2025-09-01T17:30:21.318270",
    "source": "government_detection",
    "company": "Unknown",
    "keyword": "Unknown",
    "description": "Phishing domain targeting Canadian government services",
    "sector": "government"
  },
  {
    "domain": "bc-services-verify.com",
    "category": "government",
    "score": 10.0,
    "detected_at": "2025-09-01T17:30:21.318322",
    "source": "government_detection",
    "company": "Unknown",
    "keyword": "Unknown",
    "description": "Phishing domain targeting Canadian government services",
    "sector": "government"
  },
  {
    "domain": "etransferdeposit25.com",
    "category": "government",
    "score": 10.0,
    "detected_at": "2025-09-01T17:30:21.318368",
    "source": "government_detection",
    "company": "Unknown",
    "keyword": "Unknown",
    "description": "Phishing domain targeting Canadian government services",
    "sector": "government"
  },
  {
    "domain": "cra-account-update.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.318379",
    "source": "government_detection",
    "company": "Canada Revenue Agency (CRA)",
    "keyword": "cra",
    "description": "Phishing domain impersonating Canada Revenue Agency services",
    "sector": "federal"
  },
  {
    "domain": "rcmp-secure.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.318393",
    "source": "government_detection",
    "company": "Royal Canadian Mounted Police (RCMP)",
    "keyword": "rcmp",
    "description": "Phishing domain impersonating RCMP services",
    "sector": "federal"
  },
  {
    "domain": "bc-verify.com",
    "category": "government",
    "score": 10.0,
    "detected_at": "2025-09-01T17:30:21.318444",
    "source": "government_detection",
    "company": "Unknown",
    "keyword": "Unknown",
    "description": "Phishing domain targeting Canadian government services",
    "sector": "government"
  },
  {
    "domain": "canada-transport-login.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.318478",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "ontario-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.318511",
    "source": "government_detection",
    "company": "Government of Ontario",
    "keyword": "ontario",
    "description": "Phishing domain impersonating Government of Ontario services",
    "sector": "provincial"
  },
  {
    "domain": "cra-gst-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.318527",
    "source": "government_detection",
    "company": "Canada Revenue Agency (CRA)",
    "keyword": "cra",
    "description": "Phishing domain impersonating Canada Revenue Agency services",
    "sector": "federal"
  },
  {
    "domain": "canada-eta-secure.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.318543",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "canada-etavisa.info",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.318560",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "canada-transport-secure.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.318586",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "alberta-secure.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.318623",
    "source": "government_detection",
    "company": "Government of Alberta",
    "keyword": "alberta",
    "description": "Phishing domain impersonating Government of Alberta services",
    "sector": "provincial"
  },
  {
    "domain": "canada-passport-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.318644",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "cra-refund-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.318663",
    "source": "government_detection",
    "company": "Canada Revenue Agency (CRA)",
    "keyword": "cra",
    "description": "Phishing domain impersonating Canada Revenue Agency services",
    "sector": "federal"
  },
  {
    "domain": "canadapost-package.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.318703",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "canada-transport-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.318722",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "cra-secure.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.318742",
    "source": "government_detection",
    "company": "Canada Revenue Agency (CRA)",
    "keyword": "cra",
    "description": "Phishing domain impersonating Canada Revenue Agency services",
    "sector": "federal"
  },
  {
    "domain": "canadapost-packagereschedule.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.318760",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "cra-hst-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.318796",
    "source": "government_detection",
    "company": "Canada Revenue Agency (CRA)",
    "keyword": "cra",
    "description": "Phishing domain impersonating Canada Revenue Agency services",
    "sector": "federal"
  },
  {
    "domain": "ontario-license-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.318834",
    "source": "government_detection",
    "company": "Government of Ontario",
    "keyword": "ontario",
    "description": "Phishing domain impersonating Government of Ontario services",
    "sector": "provincial"
  },
  {
    "domain": "canadapost-secure.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.318854",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "redelivauth.com",
    "category": "government",
    "score": 10.0,
    "detected_at": "2025-09-01T17:30:21.318933",
    "source": "government_detection",
    "company": "Unknown",
    "keyword": "Unknown",
    "description": "Phishing domain targeting Canadian government services",
    "sector": "government"
  },
  {
    "domain": "quebec-services-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.318971",
    "source": "government_detection",
    "company": "Government of Quebec",
    "keyword": "quebec",
    "description": "Phishing domain impersonating Government of Quebec services",
    "sector": "provincial"
  },
  {
    "domain": "cra-mobile-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.318991",
    "source": "government_detection",
    "company": "Canada Revenue Agency (CRA)",
    "keyword": "cra",
    "description": "Phishing domain impersonating Canada Revenue Agency services",
    "sector": "federal"
  },
  {
    "domain": "canada-eta-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.319009",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "cra-secure-login.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.319027",
    "source": "government_detection",
    "company": "Canada Revenue Agency (CRA)",
    "keyword": "cra",
    "description": "Phishing domain impersonating Canada Revenue Agency services",
    "sector": "federal"
  },
  {
    "domain": "servicecanada-login.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.319049",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "canada-immigration-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.319074",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "canpost-orderinfo-help.com",
    "category": "government",
    "score": 10.0,
    "detected_at": "2025-09-01T17:30:21.319153",
    "source": "government_detection",
    "company": "Unknown",
    "keyword": "Unknown",
    "description": "Phishing domain targeting Canadian government services",
    "sector": "government"
  },
  {
    "domain": "elections-canada-login.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.319187",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "rcmp-login.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.319216",
    "source": "government_detection",
    "company": "Royal Canadian Mounted Police (RCMP)",
    "keyword": "rcmp",
    "description": "Phishing domain impersonating RCMP services",
    "sector": "federal"
  },
  {
    "domain": "elections-canada-secure.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.319252",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "hstcra.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.319274",
    "source": "government_detection",
    "company": "Canada Revenue Agency (CRA)",
    "keyword": "cra",
    "description": "Phishing domain impersonating Canada Revenue Agency services",
    "sector": "federal"
  },
  {
    "domain": "gov-canada-eta.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.319292",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "ontario-health-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.319327",
    "source": "government_detection",
    "company": "Government of Ontario",
    "keyword": "ontario",
    "description": "Phishing domain impersonating Government of Ontario services",
    "sector": "provincial"
  },
  {
    "domain": "cra-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.319347",
    "source": "government_detection",
    "company": "Canada Revenue Agency (CRA)",
    "keyword": "cra",
    "description": "Phishing domain impersonating Canada Revenue Agency services",
    "sector": "federal"
  },
  {
    "domain": "quebec-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.319383",
    "source": "government_detection",
    "company": "Government of Quebec",
    "keyword": "quebec",
    "description": "Phishing domain impersonating Government of Quebec services",
    "sector": "provincial"
  },
  {
    "domain": "canadapost-delivery.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.319403",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "canada-immigration-secure.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.319424",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "servicecanada-secure.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.319442",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "reviewgsthstca.com",
    "category": "government",
    "score": 10.0,
    "detected_at": "2025-09-01T17:30:21.319544",
    "source": "government_detection",
    "company": "Unknown",
    "keyword": "Unknown",
    "description": "Phishing domain targeting Canadian government services",
    "sector": "government"
  },
  {
    "domain": "cra-account-secure.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.319572",
    "source": "government_detection",
    "company": "Canada Revenue Agency (CRA)",
    "keyword": "cra",
    "description": "Phishing domain impersonating Canada Revenue Agency services",
    "sector": "federal"
  },
  {
    "domain": "canada-border-login.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.319592",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "alberta-account-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.319615",
    "source": "government_detection",
    "company": "Government of Alberta",
    "keyword": "alberta",
    "description": "Phishing domain impersonating Government of Alberta services",
    "sector": "provincial"
  },
  {
    "domain": "canada-border-secure.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.319625",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "elections-canada-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.319634",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "setup-canada6517-post4278-now.com",
    "category": "government",
    "score": 14.0,
    "detected_at": "2025-09-01T17:30:21.319644",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "canadapost-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:30:21.319652",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  }
];
export default governmentPhishingDomains;
