const governmentPhishingDomains = [
  {
    "domain": "bc-secure.com",
    "category": "government",
    "score": 10.0,
    "detected_at": "2025-09-01T17:20:04.890188",
    "source": "government_detection",
    "company": "Unknown",
    "keyword": "Unknown",
    "description": "Phishing domain targeting Canadian government services",
    "sector": "government"
  },
  {
    "domain": "alberta-secure.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.890245",
    "source": "government_detection",
    "company": "Government of Alberta",
    "keyword": "alberta",
    "description": "Phishing domain impersonating Government of Alberta services",
    "sector": "provincial"
  },
  {
    "domain": "canada-immigration-secure.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.890258",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "canada-visa-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.890269",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "cra-secure.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.890307",
    "source": "government_detection",
    "company": "Canada Revenue Agency (CRA)",
    "keyword": "cra",
    "description": "Phishing domain impersonating Canada Revenue Agency services",
    "sector": "federal"
  },
  {
    "domain": "cra-hst-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.890319",
    "source": "government_detection",
    "company": "Canada Revenue Agency (CRA)",
    "keyword": "cra",
    "description": "Phishing domain impersonating Canada Revenue Agency services",
    "sector": "federal"
  },
  {
    "domain": "canadapost-delivery.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.890329",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "quebec-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.890346",
    "source": "government_detection",
    "company": "Government of Quebec",
    "keyword": "quebec",
    "description": "Phishing domain impersonating Government of Quebec services",
    "sector": "provincial"
  },
  {
    "domain": "canadapost-packagereschedule.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.890356",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "canada-eta-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.890365",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "canada-transport-secure.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.890375",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "redelivauth.com",
    "category": "government",
    "score": 10.0,
    "detected_at": "2025-09-01T17:20:04.890414",
    "source": "government_detection",
    "company": "Unknown",
    "keyword": "Unknown",
    "description": "Phishing domain targeting Canadian government services",
    "sector": "government"
  },
  {
    "domain": "rcmp-secure.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.890428",
    "source": "government_detection",
    "company": "Royal Canadian Mounted Police (RCMP)",
    "keyword": "rcmp",
    "description": "Phishing domain impersonating RCMP services",
    "sector": "federal"
  },
  {
    "domain": "cra-mobile-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.890438",
    "source": "government_detection",
    "company": "Canada Revenue Agency (CRA)",
    "keyword": "cra",
    "description": "Phishing domain impersonating Canada Revenue Agency services",
    "sector": "federal"
  },
  {
    "domain": "hstcra.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.890446",
    "source": "government_detection",
    "company": "Canada Revenue Agency (CRA)",
    "keyword": "cra",
    "description": "Phishing domain impersonating Canada Revenue Agency services",
    "sector": "federal"
  },
  {
    "domain": "cra-gst-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.890455",
    "source": "government_detection",
    "company": "Canada Revenue Agency (CRA)",
    "keyword": "cra",
    "description": "Phishing domain impersonating Canada Revenue Agency services",
    "sector": "federal"
  },
  {
    "domain": "canada-passport-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.890476",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "gov-canada-eta.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.890494",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "cra-refund-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.890504",
    "source": "government_detection",
    "company": "Canada Revenue Agency (CRA)",
    "keyword": "cra",
    "description": "Phishing domain impersonating Canada Revenue Agency services",
    "sector": "federal"
  },
  {
    "domain": "quebec-services-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.890522",
    "source": "government_detection",
    "company": "Government of Quebec",
    "keyword": "quebec",
    "description": "Phishing domain impersonating Government of Quebec services",
    "sector": "provincial"
  },
  {
    "domain": "ontario-health-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.890538",
    "source": "government_detection",
    "company": "Government of Ontario",
    "keyword": "ontario",
    "description": "Phishing domain impersonating Government of Ontario services",
    "sector": "provincial"
  },
  {
    "domain": "ontario-secure.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.890555",
    "source": "government_detection",
    "company": "Government of Ontario",
    "keyword": "ontario",
    "description": "Phishing domain impersonating Government of Ontario services",
    "sector": "provincial"
  },
  {
    "domain": "canada-transport-login.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.890564",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "cra-online-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.890574",
    "source": "government_detection",
    "company": "Canada Revenue Agency (CRA)",
    "keyword": "cra",
    "description": "Phishing domain impersonating Canada Revenue Agency services",
    "sector": "federal"
  },
  {
    "domain": "canadapost-secure.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.890582",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "ontario-license-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.890599",
    "source": "government_detection",
    "company": "Government of Ontario",
    "keyword": "ontario",
    "description": "Phishing domain impersonating Government of Ontario services",
    "sector": "provincial"
  },
  {
    "domain": "alberta-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.890617",
    "source": "government_detection",
    "company": "Government of Alberta",
    "keyword": "alberta",
    "description": "Phishing domain impersonating Government of Alberta services",
    "sector": "provincial"
  },
  {
    "domain": "canpost-orderinfo-help.com",
    "category": "government",
    "score": 10.0,
    "detected_at": "2025-09-01T17:20:04.890656",
    "source": "government_detection",
    "company": "Unknown",
    "keyword": "Unknown",
    "description": "Phishing domain targeting Canadian government services",
    "sector": "government"
  },
  {
    "domain": "canadapost-account.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.890666",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "ontario-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.890682",
    "source": "government_detection",
    "company": "Government of Ontario",
    "keyword": "ontario",
    "description": "Phishing domain impersonating Government of Ontario services",
    "sector": "provincial"
  },
  {
    "domain": "canadapost-package.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.890702",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "canada-border-secure.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.890712",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "canada-immigration-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.890721",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "canadapost-login.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.890730",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "canadapost-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.890739",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "bc-verify.com",
    "category": "government",
    "score": 10.0,
    "detected_at": "2025-09-01T17:20:04.890786",
    "source": "government_detection",
    "company": "Unknown",
    "keyword": "Unknown",
    "description": "Phishing domain targeting Canadian government services",
    "sector": "government"
  },
  {
    "domain": "rcmp-login.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.890801",
    "source": "government_detection",
    "company": "Royal Canadian Mounted Police (RCMP)",
    "keyword": "rcmp",
    "description": "Phishing domain impersonating RCMP services",
    "sector": "federal"
  },
  {
    "domain": "etransferdeposit25.com",
    "category": "government",
    "score": 10.0,
    "detected_at": "2025-09-01T17:20:04.890839",
    "source": "government_detection",
    "company": "Unknown",
    "keyword": "Unknown",
    "description": "Phishing domain targeting Canadian government services",
    "sector": "government"
  },
  {
    "domain": "redelivercadpost.com",
    "category": "government",
    "score": 10.0,
    "detected_at": "2025-09-01T17:20:04.890878",
    "source": "government_detection",
    "company": "Unknown",
    "keyword": "Unknown",
    "description": "Phishing domain targeting Canadian government services",
    "sector": "government"
  },
  {
    "domain": "canada-etavisa.info",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.890887",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "cra-account-update.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.890897",
    "source": "government_detection",
    "company": "Canada Revenue Agency (CRA)",
    "keyword": "cra",
    "description": "Phishing domain impersonating Canada Revenue Agency services",
    "sector": "federal"
  },
  {
    "domain": "elections-canada-secure.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.890907",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "canada-passport-secure.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.890916",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "alberta-account-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.890943",
    "source": "government_detection",
    "company": "Government of Alberta",
    "keyword": "alberta",
    "description": "Phishing domain impersonating Government of Alberta services",
    "sector": "provincial"
  },
  {
    "domain": "elections-canada-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.890953",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "elections-canada-login.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.890962",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "canada-border-login.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.890971",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "canada-visa-secure.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.890981",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "cra-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.890997",
    "source": "government_detection",
    "company": "Canada Revenue Agency (CRA)",
    "keyword": "cra",
    "description": "Phishing domain impersonating Canada Revenue Agency services",
    "sector": "federal"
  },
  {
    "domain": "cra-login-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.891009",
    "source": "government_detection",
    "company": "Canada Revenue Agency (CRA)",
    "keyword": "cra",
    "description": "Phishing domain impersonating Canada Revenue Agency services",
    "sector": "federal"
  },
  {
    "domain": "bc-services-verify.com",
    "category": "government",
    "score": 10.0,
    "detected_at": "2025-09-01T17:20:04.891048",
    "source": "government_detection",
    "company": "Unknown",
    "keyword": "Unknown",
    "description": "Phishing domain targeting Canadian government services",
    "sector": "government"
  },
  {
    "domain": "rcmp-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.891062",
    "source": "government_detection",
    "company": "Royal Canadian Mounted Police (RCMP)",
    "keyword": "rcmp",
    "description": "Phishing domain impersonating RCMP services",
    "sector": "federal"
  },
  {
    "domain": "cra-secure-login.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.891074",
    "source": "government_detection",
    "company": "Canada Revenue Agency (CRA)",
    "keyword": "cra",
    "description": "Phishing domain impersonating Canada Revenue Agency services",
    "sector": "federal"
  },
  {
    "domain": "canada-transport-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.891083",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "servicecanada-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.891092",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "authhstdeposit.com",
    "category": "government",
    "score": 10.0,
    "detected_at": "2025-09-01T17:20:04.891130",
    "source": "government_detection",
    "company": "Unknown",
    "keyword": "Unknown",
    "description": "Phishing domain targeting Canadian government services",
    "sector": "government"
  },
  {
    "domain": "setup-canada6517-post4278-now.com",
    "category": "government",
    "score": 14.0,
    "detected_at": "2025-09-01T17:20:04.891149",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "canada-border-verify.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.891159",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "canadapost-tracking.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.891168",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "canada-eta-secure.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.891178",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "servicecanada-secure.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.891187",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "servicecanada-login.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.891196",
    "source": "government_detection",
    "company": "Government of Canada",
    "keyword": "canada",
    "description": "Phishing domain impersonating Government of Canada services",
    "sector": "federal"
  },
  {
    "domain": "reviewgsthstca.com",
    "category": "government",
    "score": 10.0,
    "detected_at": "2025-09-01T17:20:04.891236",
    "source": "government_detection",
    "company": "Unknown",
    "keyword": "Unknown",
    "description": "Phishing domain targeting Canadian government services",
    "sector": "government"
  },
  {
    "domain": "cra-account-secure.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.891246",
    "source": "government_detection",
    "company": "Canada Revenue Agency (CRA)",
    "keyword": "cra",
    "description": "Phishing domain impersonating Canada Revenue Agency services",
    "sector": "federal"
  },
  {
    "domain": "quebec-secure.com",
    "category": "government",
    "score": 13.0,
    "detected_at": "2025-09-01T17:20:04.891263",
    "source": "government_detection",
    "company": "Government of Quebec",
    "keyword": "quebec",
    "description": "Phishing domain impersonating Government of Quebec services",
    "sector": "provincial"
  }
];
export default governmentPhishingDomains;
