const canadianBankPhishingDomains = [
  {
    "domain": "vancity-verify.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.163242",
    "source": "banking_detection",
    "company": "Vancity Credit Union",
    "keyword": "vancity",
    "description": "Phishing domain impersonating Vancity Credit Union services",
    "sector": "banking"
  },
  {
    "domain": "cibc-mobile-app.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.163312",
    "source": "banking_detection",
    "company": "CIBC",
    "keyword": "cibc",
    "description": "Phishing domain impersonating Canadian Imperial Bank of Commerce services",
    "sector": "banking"
  },
  {
    "domain": "td-secure-login.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.163335",
    "source": "banking_detection",
    "company": "TD Bank",
    "keyword": "td",
    "description": "Phishing domain impersonating TD Bank services",
    "sector": "banking"
  },
  {
    "domain": "desjardins-verify.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.163355",
    "source": "banking_detection",
    "company": "Desjardins Group",
    "keyword": "desjardins",
    "description": "Phishing domain impersonating Desjardins credit union services",
    "sector": "banking"
  },
  {
    "domain": "rbc-mobile-app.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.163367",
    "source": "banking_detection",
    "company": "RBC",
    "keyword": "rbc",
    "description": "Phishing domain impersonating Royal Bank of Canada services",
    "sector": "banking"
  },
  {
    "domain": "bmo-secure-access.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.163379",
    "source": "banking_detection",
    "company": "BMO",
    "keyword": "bmo",
    "description": "Phishing domain impersonating Bank of Montreal services",
    "sector": "banking"
  },
  {
    "domain": "online-cibc-secure.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.163391",
    "source": "banking_detection",
    "company": "CIBC",
    "keyword": "cibc",
    "description": "Phishing domain impersonating Canadian Imperial Bank of Commerce services",
    "sector": "banking"
  },
  {
    "domain": "td-secure-access.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.163400",
    "source": "banking_detection",
    "company": "TD Bank",
    "keyword": "td",
    "description": "Phishing domain impersonating TD Bank services",
    "sector": "banking"
  },
  {
    "domain": "koho-verify.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.163843",
    "source": "banking_detection",
    "company": "Koho",
    "keyword": "koho",
    "description": "Phishing domain impersonating Koho financial services",
    "sector": "banking"
  },
  {
    "domain": "eqbank-verify.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.163885",
    "source": "banking_detection",
    "company": "EQ Bank",
    "keyword": "eqbank",
    "description": "Phishing domain impersonating EQ Bank services",
    "sector": "banking"
  },
  {
    "domain": "tangerine-verify.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.163902",
    "source": "banking_detection",
    "company": "Tangerine Bank",
    "keyword": "tangerine",
    "description": "Phishing domain impersonating Tangerine Bank services",
    "sector": "banking"
  },
  {
    "domain": "td-verify-account.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.163913",
    "source": "banking_detection",
    "company": "TD Bank",
    "keyword": "td",
    "description": "Phishing domain impersonating TD Bank services",
    "sector": "banking"
  },
  {
    "domain": "td-online-banking.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.163923",
    "source": "banking_detection",
    "company": "TD Bank",
    "keyword": "td",
    "description": "Phishing domain impersonating TD Bank services",
    "sector": "banking"
  },
  {
    "domain": "scotia-account-update.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.163932",
    "source": "banking_detection",
    "company": "Scotiabank",
    "keyword": "scotia",
    "description": "Phishing domain impersonating Scotiabank banking services",
    "sector": "banking"
  },
  {
    "domain": "hsbc-canada-secure.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.163946",
    "source": "banking_detection",
    "company": "HSBC Canada",
    "keyword": "hsbc",
    "description": "Phishing domain impersonating HSBC Canada services",
    "sector": "banking"
  },
  {
    "domain": "bmo-verify.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.163957",
    "source": "banking_detection",
    "company": "BMO",
    "keyword": "bmo",
    "description": "Phishing domain impersonating Bank of Montreal services",
    "sector": "banking"
  },
  {
    "domain": "coastcapitalsavings-secure.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.163988",
    "source": "banking_detection",
    "company": "Coast Capital Savings",
    "keyword": "coastcapitalsavings",
    "description": "Phishing domain impersonating Coast Capital Savings services",
    "sector": "banking"
  },
  {
    "domain": "rbc-secure-access.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.164008",
    "source": "banking_detection",
    "company": "RBC",
    "keyword": "rbc",
    "description": "Phishing domain impersonating Royal Bank of Canada services",
    "sector": "banking"
  },
  {
    "domain": "cibc-mobile-banking.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.164025",
    "source": "banking_detection",
    "company": "CIBC",
    "keyword": "cibc",
    "description": "Phishing domain impersonating Canadian Imperial Bank of Commerce services",
    "sector": "banking"
  },
  {
    "domain": "mobile-td-app.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.164034",
    "source": "banking_detection",
    "company": "TD Bank",
    "keyword": "td",
    "description": "Phishing domain impersonating TD Bank services",
    "sector": "banking"
  },
  {
    "domain": "scotia-mobile-banking.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.164043",
    "source": "banking_detection",
    "company": "Scotiabank",
    "keyword": "scotia",
    "description": "Phishing domain impersonating Scotiabank banking services",
    "sector": "banking"
  },
  {
    "domain": "motivefinancial-secure.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.164063",
    "source": "banking_detection",
    "company": "Motive Financial",
    "keyword": "motivefinancial",
    "description": "Phishing domain impersonating Motive Financial services",
    "sector": "banking"
  },
  {
    "domain": "scotia-secure-access.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.164072",
    "source": "banking_detection",
    "company": "Scotiabank",
    "keyword": "scotia",
    "description": "Phishing domain impersonating Scotiabank banking services",
    "sector": "banking"
  },
  {
    "domain": "rbc-mobile-banking.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.164082",
    "source": "banking_detection",
    "company": "RBC",
    "keyword": "rbc",
    "description": "Phishing domain impersonating Royal Bank of Canada services",
    "sector": "banking"
  },
  {
    "domain": "laurentianbank-secure.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.164096",
    "source": "banking_detection",
    "company": "Laurentian Bank",
    "keyword": "laurentianbank",
    "description": "Phishing domain impersonating Laurentian Bank services",
    "sector": "banking"
  },
  {
    "domain": "td-mobile-banking.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.164111",
    "source": "banking_detection",
    "company": "TD Bank",
    "keyword": "td",
    "description": "Phishing domain impersonating TD Bank services",
    "sector": "banking"
  },
  {
    "domain": "cibc-verify.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.164141",
    "source": "banking_detection",
    "company": "CIBC",
    "keyword": "cibc",
    "description": "Phishing domain impersonating Canadian Imperial Bank of Commerce services",
    "sector": "banking"
  },
  {
    "domain": "servus-verify.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.164171",
    "source": "banking_detection",
    "company": "Servus Credit Union",
    "keyword": "servus",
    "description": "Phishing domain impersonating Servus Credit Union services",
    "sector": "banking"
  },
  {
    "domain": "verify-scotiabank.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.164187",
    "source": "banking_detection",
    "company": "Scotiabank",
    "keyword": "scotia",
    "description": "Phishing domain impersonating Scotiabank banking services",
    "sector": "banking"
  },
  {
    "domain": "td-verification.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.164203",
    "source": "banking_detection",
    "company": "TD Bank",
    "keyword": "td",
    "description": "Phishing domain impersonating TD Bank services",
    "sector": "banking"
  },
  {
    "domain": "cibc-online-banking.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.164234",
    "source": "banking_detection",
    "company": "CIBC",
    "keyword": "cibc",
    "description": "Phishing domain impersonating Canadian Imperial Bank of Commerce services",
    "sector": "banking"
  },
  {
    "domain": "wealthsimple-secure.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.164351",
    "source": "banking_detection",
    "company": "Wealthsimple",
    "keyword": "wealthsimple",
    "description": "Phishing domain impersonating Wealthsimple financial services",
    "sector": "banking"
  },
  {
    "domain": "secure-td-bank.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.164368",
    "source": "banking_detection",
    "company": "TD Bank",
    "keyword": "td",
    "description": "Phishing domain impersonating TD Bank services",
    "sector": "banking"
  },
  {
    "domain": "scotia-online.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.164383",
    "source": "banking_detection",
    "company": "Scotiabank",
    "keyword": "scotia",
    "description": "Phishing domain impersonating Scotiabank banking services",
    "sector": "banking"
  },
  {
    "domain": "bmo-secure-login.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.164394",
    "source": "banking_detection",
    "company": "BMO",
    "keyword": "bmo",
    "description": "Phishing domain impersonating Bank of Montreal services",
    "sector": "banking"
  },
  {
    "domain": "bmo-online-banking.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.164454",
    "source": "banking_detection",
    "company": "BMO",
    "keyword": "bmo",
    "description": "Phishing domain impersonating Bank of Montreal services",
    "sector": "banking"
  },
  {
    "domain": "login-rbc-online.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.164471",
    "source": "banking_detection",
    "company": "RBC",
    "keyword": "rbc",
    "description": "Phishing domain impersonating Royal Bank of Canada services",
    "sector": "banking"
  },
  {
    "domain": "rbc-verification.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.164482",
    "source": "banking_detection",
    "company": "RBC",
    "keyword": "rbc",
    "description": "Phishing domain impersonating Royal Bank of Canada services",
    "sector": "banking"
  },
  {
    "domain": "alternabank-secure.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.164500",
    "source": "banking_detection",
    "company": "Alterna Bank",
    "keyword": "alternabank",
    "description": "Phishing domain impersonating Alterna Bank services",
    "sector": "banking"
  },
  {
    "domain": "bmo-verification.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.164511",
    "source": "banking_detection",
    "company": "BMO",
    "keyword": "bmo",
    "description": "Phishing domain impersonating Bank of Montreal services",
    "sector": "banking"
  },
  {
    "domain": "td-account-update.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.164521",
    "source": "banking_detection",
    "company": "TD Bank",
    "keyword": "td",
    "description": "Phishing domain impersonating TD Bank services",
    "sector": "banking"
  },
  {
    "domain": "bmo-mobile-banking.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.164531",
    "source": "banking_detection",
    "company": "BMO",
    "keyword": "bmo",
    "description": "Phishing domain impersonating Bank of Montreal services",
    "sector": "banking"
  },
  {
    "domain": "bmo-online.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.164542",
    "source": "banking_detection",
    "company": "BMO",
    "keyword": "bmo",
    "description": "Phishing domain impersonating Bank of Montreal services",
    "sector": "banking"
  },
  {
    "domain": "simplii-verify.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.164565",
    "source": "banking_detection",
    "company": "Simplii Financial",
    "keyword": "simplii",
    "description": "Phishing domain impersonating Simplii Financial services",
    "sector": "banking"
  },
  {
    "domain": "bmo-mobile-app.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.164576",
    "source": "banking_detection",
    "company": "BMO",
    "keyword": "bmo",
    "description": "Phishing domain impersonating Bank of Montreal services",
    "sector": "banking"
  },
  {
    "domain": "rbc-secure-login.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.164586",
    "source": "banking_detection",
    "company": "RBC",
    "keyword": "rbc",
    "description": "Phishing domain impersonating Royal Bank of Canada services",
    "sector": "banking"
  },
  {
    "domain": "cibc-secure-login.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.164597",
    "source": "banking_detection",
    "company": "CIBC",
    "keyword": "cibc",
    "description": "Phishing domain impersonating Canadian Imperial Bank of Commerce services",
    "sector": "banking"
  },
  {
    "domain": "rbc-account-update.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.164608",
    "source": "banking_detection",
    "company": "RBC",
    "keyword": "rbc",
    "description": "Phishing domain impersonating Royal Bank of Canada services",
    "sector": "banking"
  },
  {
    "domain": "rbc-online-banking.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.164618",
    "source": "banking_detection",
    "company": "RBC",
    "keyword": "rbc",
    "description": "Phishing domain impersonating Royal Bank of Canada services",
    "sector": "banking"
  },
  {
    "domain": "scotia-secure-login.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.164626",
    "source": "banking_detection",
    "company": "Scotiabank",
    "keyword": "scotia",
    "description": "Phishing domain impersonating Scotiabank banking services",
    "sector": "banking"
  },
  {
    "domain": "scotia-mobile-app.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.164635",
    "source": "banking_detection",
    "company": "Scotiabank",
    "keyword": "scotia",
    "description": "Phishing domain impersonating Scotiabank banking services",
    "sector": "banking"
  },
  {
    "domain": "update-bmo-account.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.164646",
    "source": "banking_detection",
    "company": "BMO",
    "keyword": "bmo",
    "description": "Phishing domain impersonating Bank of Montreal services",
    "sector": "banking"
  },
  {
    "domain": "pcfinancial-secure.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.164666",
    "source": "banking_detection",
    "company": "PC Financial",
    "keyword": "pcfinancial",
    "description": "Phishing domain impersonating PC Financial services",
    "sector": "banking"
  },
  {
    "domain": "cibc-account-update.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.164678",
    "source": "banking_detection",
    "company": "CIBC",
    "keyword": "cibc",
    "description": "Phishing domain impersonating Canadian Imperial Bank of Commerce services",
    "sector": "banking"
  },
  {
    "domain": "cibc-verification.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.164690",
    "source": "banking_detection",
    "company": "CIBC",
    "keyword": "cibc",
    "description": "Phishing domain impersonating Canadian Imperial Bank of Commerce services",
    "sector": "banking"
  },
  {
    "domain": "cibc-secure-access.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.164701",
    "source": "banking_detection",
    "company": "CIBC",
    "keyword": "cibc",
    "description": "Phishing domain impersonating Canadian Imperial Bank of Commerce services",
    "sector": "banking"
  },
  {
    "domain": "scotia-online-banking.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.164714",
    "source": "banking_detection",
    "company": "Scotiabank",
    "keyword": "scotia",
    "description": "Phishing domain impersonating Scotiabank banking services",
    "sector": "banking"
  },
  {
    "domain": "rbc-verify.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.164723",
    "source": "banking_detection",
    "company": "RBC",
    "keyword": "rbc",
    "description": "Phishing domain impersonating Royal Bank of Canada services",
    "sector": "banking"
  },
  {
    "domain": "nationalbank-secure.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.164735",
    "source": "banking_detection",
    "company": "National Bank of Canada",
    "keyword": "nationalbank",
    "description": "Phishing domain impersonating National Bank of Canada services",
    "sector": "banking"
  },
  {
    "domain": "scotia-verify.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.164745",
    "source": "banking_detection",
    "company": "Scotiabank",
    "keyword": "scotia",
    "description": "Phishing domain impersonating Scotiabank banking services",
    "sector": "banking"
  },
  {
    "domain": "atb-secure.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T17:22:54.164759",
    "source": "banking_detection",
    "company": "ATB Financial",
    "keyword": "atb",
    "description": "Phishing domain impersonating ATB Financial services",
    "sector": "banking"
  }
];
export default canadianBankPhishingDomains;
