const canadianBankPhishingDomains = [
  {
    "domain": "wealthsimple-secure.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.412594",
    "source": "banking_detection",
    "company": "Wealthsimple",
    "keyword": "wealthsimple",
    "description": "Phishing domain impersonating Wealthsimple financial services",
    "sector": "banking"
  },
  {
    "domain": "scotia-online.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.412669",
    "source": "banking_detection",
    "company": "Scotiabank",
    "keyword": "scotia",
    "description": "Phishing domain impersonating Scotiabank banking services",
    "sector": "banking"
  },
  {
    "domain": "rbc-secure-access.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.412691",
    "source": "banking_detection",
    "company": "RBC",
    "keyword": "rbc",
    "description": "Phishing domain impersonating Royal Bank of Canada services",
    "sector": "banking"
  },
  {
    "domain": "rbc-online-banking.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.412708",
    "source": "banking_detection",
    "company": "RBC",
    "keyword": "rbc",
    "description": "Phishing domain impersonating Royal Bank of Canada services",
    "sector": "banking"
  },
  {
    "domain": "bmo-verification.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.412727",
    "source": "banking_detection",
    "company": "BMO",
    "keyword": "bmo",
    "description": "Phishing domain impersonating Bank of Montreal services",
    "sector": "banking"
  },
  {
    "domain": "scotia-secure-login.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.412746",
    "source": "banking_detection",
    "company": "Scotiabank",
    "keyword": "scotia",
    "description": "Phishing domain impersonating Scotiabank banking services",
    "sector": "banking"
  },
  {
    "domain": "laurentianbank-secure.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.412776",
    "source": "banking_detection",
    "company": "Laurentian Bank",
    "keyword": "laurentianbank",
    "description": "Phishing domain impersonating Laurentian Bank services",
    "sector": "banking"
  },
  {
    "domain": "td-secure-access.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.412796",
    "source": "banking_detection",
    "company": "TD Bank",
    "keyword": "td",
    "description": "Phishing domain impersonating TD Bank services",
    "sector": "banking"
  },
  {
    "domain": "online-cibc-secure.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.412821",
    "source": "banking_detection",
    "company": "CIBC",
    "keyword": "cibc",
    "description": "Phishing domain impersonating Canadian Imperial Bank of Commerce services",
    "sector": "banking"
  },
  {
    "domain": "alternabank-secure.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.412856",
    "source": "banking_detection",
    "company": "Alterna Bank",
    "keyword": "alternabank",
    "description": "Phishing domain impersonating Alterna Bank services",
    "sector": "banking"
  },
  {
    "domain": "td-account-update.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.412877",
    "source": "banking_detection",
    "company": "TD Bank",
    "keyword": "td",
    "description": "Phishing domain impersonating TD Bank services",
    "sector": "banking"
  },
  {
    "domain": "td-mobile-banking.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.412896",
    "source": "banking_detection",
    "company": "TD Bank",
    "keyword": "td",
    "description": "Phishing domain impersonating TD Bank services",
    "sector": "banking"
  },
  {
    "domain": "mobile-td-app.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.412927",
    "source": "banking_detection",
    "company": "TD Bank",
    "keyword": "td",
    "description": "Phishing domain impersonating TD Bank services",
    "sector": "banking"
  },
  {
    "domain": "td-online-banking.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.412945",
    "source": "banking_detection",
    "company": "TD Bank",
    "keyword": "td",
    "description": "Phishing domain impersonating TD Bank services",
    "sector": "banking"
  },
  {
    "domain": "td-verify-account.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.412961",
    "source": "banking_detection",
    "company": "TD Bank",
    "keyword": "td",
    "description": "Phishing domain impersonating TD Bank services",
    "sector": "banking"
  },
  {
    "domain": "cibc-secure-login.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.412981",
    "source": "banking_detection",
    "company": "CIBC",
    "keyword": "cibc",
    "description": "Phishing domain impersonating Canadian Imperial Bank of Commerce services",
    "sector": "banking"
  },
  {
    "domain": "cibc-mobile-banking.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.413016",
    "source": "banking_detection",
    "company": "CIBC",
    "keyword": "cibc",
    "description": "Phishing domain impersonating Canadian Imperial Bank of Commerce services",
    "sector": "banking"
  },
  {
    "domain": "cibc-account-update.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.413038",
    "source": "banking_detection",
    "company": "CIBC",
    "keyword": "cibc",
    "description": "Phishing domain impersonating Canadian Imperial Bank of Commerce services",
    "sector": "banking"
  },
  {
    "domain": "tangerine-verify.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.413062",
    "source": "banking_detection",
    "company": "Tangerine Bank",
    "keyword": "tangerine",
    "description": "Phishing domain impersonating Tangerine Bank services",
    "sector": "banking"
  },
  {
    "domain": "servus-verify.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.413089",
    "source": "banking_detection",
    "company": "Servus Credit Union",
    "keyword": "servus",
    "description": "Phishing domain impersonating Servus Credit Union services",
    "sector": "banking"
  },
  {
    "domain": "bmo-online.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.413110",
    "source": "banking_detection",
    "company": "BMO",
    "keyword": "bmo",
    "description": "Phishing domain impersonating Bank of Montreal services",
    "sector": "banking"
  },
  {
    "domain": "bmo-online-banking.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.413132",
    "source": "banking_detection",
    "company": "BMO",
    "keyword": "bmo",
    "description": "Phishing domain impersonating Bank of Montreal services",
    "sector": "banking"
  },
  {
    "domain": "rbc-verification.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.413152",
    "source": "banking_detection",
    "company": "RBC",
    "keyword": "rbc",
    "description": "Phishing domain impersonating Royal Bank of Canada services",
    "sector": "banking"
  },
  {
    "domain": "scotia-verify.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.413170",
    "source": "banking_detection",
    "company": "Scotiabank",
    "keyword": "scotia",
    "description": "Phishing domain impersonating Scotiabank banking services",
    "sector": "banking"
  },
  {
    "domain": "rbc-account-update.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.413189",
    "source": "banking_detection",
    "company": "RBC",
    "keyword": "rbc",
    "description": "Phishing domain impersonating Royal Bank of Canada services",
    "sector": "banking"
  },
  {
    "domain": "scotia-online-banking.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.413208",
    "source": "banking_detection",
    "company": "Scotiabank",
    "keyword": "scotia",
    "description": "Phishing domain impersonating Scotiabank banking services",
    "sector": "banking"
  },
  {
    "domain": "bmo-mobile-banking.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.413229",
    "source": "banking_detection",
    "company": "BMO",
    "keyword": "bmo",
    "description": "Phishing domain impersonating Bank of Montreal services",
    "sector": "banking"
  },
  {
    "domain": "cibc-online-banking.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.413253",
    "source": "banking_detection",
    "company": "CIBC",
    "keyword": "cibc",
    "description": "Phishing domain impersonating Canadian Imperial Bank of Commerce services",
    "sector": "banking"
  },
  {
    "domain": "cibc-verify.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.413276",
    "source": "banking_detection",
    "company": "CIBC",
    "keyword": "cibc",
    "description": "Phishing domain impersonating Canadian Imperial Bank of Commerce services",
    "sector": "banking"
  },
  {
    "domain": "hsbc-canada-secure.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.413311",
    "source": "banking_detection",
    "company": "HSBC Canada",
    "keyword": "hsbc",
    "description": "Phishing domain impersonating HSBC Canada services",
    "sector": "banking"
  },
  {
    "domain": "pcfinancial-secure.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.413351",
    "source": "banking_detection",
    "company": "PC Financial",
    "keyword": "pcfinancial",
    "description": "Phishing domain impersonating PC Financial services",
    "sector": "banking"
  },
  {
    "domain": "rbc-mobile-banking.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.413373",
    "source": "banking_detection",
    "company": "RBC",
    "keyword": "rbc",
    "description": "Phishing domain impersonating Royal Bank of Canada services",
    "sector": "banking"
  },
  {
    "domain": "scotia-mobile-banking.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.413392",
    "source": "banking_detection",
    "company": "Scotiabank",
    "keyword": "scotia",
    "description": "Phishing domain impersonating Scotiabank banking services",
    "sector": "banking"
  },
  {
    "domain": "bmo-secure-login.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.413413",
    "source": "banking_detection",
    "company": "BMO",
    "keyword": "bmo",
    "description": "Phishing domain impersonating Bank of Montreal services",
    "sector": "banking"
  },
  {
    "domain": "verify-scotiabank.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.413431",
    "source": "banking_detection",
    "company": "Scotiabank",
    "keyword": "scotia",
    "description": "Phishing domain impersonating Scotiabank banking services",
    "sector": "banking"
  },
  {
    "domain": "bmo-secure-access.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.413453",
    "source": "banking_detection",
    "company": "BMO",
    "keyword": "bmo",
    "description": "Phishing domain impersonating Bank of Montreal services",
    "sector": "banking"
  },
  {
    "domain": "koho-verify.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.413499",
    "source": "banking_detection",
    "company": "Koho",
    "keyword": "koho",
    "description": "Phishing domain impersonating Koho financial services",
    "sector": "banking"
  },
  {
    "domain": "coastcapitalsavings-secure.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.413534",
    "source": "banking_detection",
    "company": "Coast Capital Savings",
    "keyword": "coastcapitalsavings",
    "description": "Phishing domain impersonating Coast Capital Savings services",
    "sector": "banking"
  },
  {
    "domain": "scotia-mobile-app.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.413553",
    "source": "banking_detection",
    "company": "Scotiabank",
    "keyword": "scotia",
    "description": "Phishing domain impersonating Scotiabank banking services",
    "sector": "banking"
  },
  {
    "domain": "rbc-mobile-app.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.413572",
    "source": "banking_detection",
    "company": "RBC",
    "keyword": "rbc",
    "description": "Phishing domain impersonating Royal Bank of Canada services",
    "sector": "banking"
  },
  {
    "domain": "scotia-secure-access.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.413600",
    "source": "banking_detection",
    "company": "Scotiabank",
    "keyword": "scotia",
    "description": "Phishing domain impersonating Scotiabank banking services",
    "sector": "banking"
  },
  {
    "domain": "td-secure-login.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.413625",
    "source": "banking_detection",
    "company": "TD Bank",
    "keyword": "td",
    "description": "Phishing domain impersonating TD Bank services",
    "sector": "banking"
  },
  {
    "domain": "rbc-verify.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.413650",
    "source": "banking_detection",
    "company": "RBC",
    "keyword": "rbc",
    "description": "Phishing domain impersonating Royal Bank of Canada services",
    "sector": "banking"
  },
  {
    "domain": "rbc-secure-login.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.413671",
    "source": "banking_detection",
    "company": "RBC",
    "keyword": "rbc",
    "description": "Phishing domain impersonating Royal Bank of Canada services",
    "sector": "banking"
  },
  {
    "domain": "scotia-account-update.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.413690",
    "source": "banking_detection",
    "company": "Scotiabank",
    "keyword": "scotia",
    "description": "Phishing domain impersonating Scotiabank banking services",
    "sector": "banking"
  },
  {
    "domain": "bmo-verify.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.413710",
    "source": "banking_detection",
    "company": "BMO",
    "keyword": "bmo",
    "description": "Phishing domain impersonating Bank of Montreal services",
    "sector": "banking"
  },
  {
    "domain": "atb-secure.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.413739",
    "source": "banking_detection",
    "company": "ATB Financial",
    "keyword": "atb",
    "description": "Phishing domain impersonating ATB Financial services",
    "sector": "banking"
  },
  {
    "domain": "secure-td-bank.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.413760",
    "source": "banking_detection",
    "company": "TD Bank",
    "keyword": "td",
    "description": "Phishing domain impersonating TD Bank services",
    "sector": "banking"
  },
  {
    "domain": "cibc-mobile-app.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.413784",
    "source": "banking_detection",
    "company": "CIBC",
    "keyword": "cibc",
    "description": "Phishing domain impersonating Canadian Imperial Bank of Commerce services",
    "sector": "banking"
  },
  {
    "domain": "login-rbc-online.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.413811",
    "source": "banking_detection",
    "company": "RBC",
    "keyword": "rbc",
    "description": "Phishing domain impersonating Royal Bank of Canada services",
    "sector": "banking"
  },
  {
    "domain": "nationalbank-secure.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.413835",
    "source": "banking_detection",
    "company": "National Bank of Canada",
    "keyword": "nationalbank",
    "description": "Phishing domain impersonating National Bank of Canada services",
    "sector": "banking"
  },
  {
    "domain": "td-verification.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.413855",
    "source": "banking_detection",
    "company": "TD Bank",
    "keyword": "td",
    "description": "Phishing domain impersonating TD Bank services",
    "sector": "banking"
  },
  {
    "domain": "update-bmo-account.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.413876",
    "source": "banking_detection",
    "company": "BMO",
    "keyword": "bmo",
    "description": "Phishing domain impersonating Bank of Montreal services",
    "sector": "banking"
  },
  {
    "domain": "simplii-verify.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.413924",
    "source": "banking_detection",
    "company": "Simplii Financial",
    "keyword": "simplii",
    "description": "Phishing domain impersonating Simplii Financial services",
    "sector": "banking"
  },
  {
    "domain": "desjardins-verify.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.413957",
    "source": "banking_detection",
    "company": "Desjardins Group",
    "keyword": "desjardins",
    "description": "Phishing domain impersonating Desjardins credit union services",
    "sector": "banking"
  },
  {
    "domain": "cibc-verification.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.413987",
    "source": "banking_detection",
    "company": "CIBC",
    "keyword": "cibc",
    "description": "Phishing domain impersonating Canadian Imperial Bank of Commerce services",
    "sector": "banking"
  },
  {
    "domain": "bmo-mobile-app.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.414010",
    "source": "banking_detection",
    "company": "BMO",
    "keyword": "bmo",
    "description": "Phishing domain impersonating Bank of Montreal services",
    "sector": "banking"
  },
  {
    "domain": "cibc-secure-access.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.414033",
    "source": "banking_detection",
    "company": "CIBC",
    "keyword": "cibc",
    "description": "Phishing domain impersonating Canadian Imperial Bank of Commerce services",
    "sector": "banking"
  },
  {
    "domain": "eqbank-verify.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.414068",
    "source": "banking_detection",
    "company": "EQ Bank",
    "keyword": "eqbank",
    "description": "Phishing domain impersonating EQ Bank services",
    "sector": "banking"
  },
  {
    "domain": "motivefinancial-secure.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.414108",
    "source": "banking_detection",
    "company": "Motive Financial",
    "keyword": "motivefinancial",
    "description": "Phishing domain impersonating Motive Financial services",
    "sector": "banking"
  },
  {
    "domain": "vancity-verify.com",
    "category": "banking",
    "score": 13.0,
    "detected_at": "2025-09-01T15:48:39.414140",
    "source": "banking_detection",
    "company": "Vancity Credit Union",
    "keyword": "vancity",
    "description": "Phishing domain impersonating Vancity Credit Union services",
    "sector": "banking"
  }
];
export default canadianBankPhishingDomains;
